// Embed all game assets into a C header as byte arrays.
const fs = require("fs");
const path = require("path");
const dir = "C:/proy/zombis/ZamnNative/assets";
const files = ["zeke.png", "julie.png", "zombie.png", "victims.png", "items.png", "exitdoor.png", "level_big.png", "walk_big.bin"];
let out = "/* generated by embed.js - all game assets embedded */\n";
for (const f of files) {
  const data = fs.readFileSync(path.join(dir, f));
  const name = "emb_" + f.replace(/[.-]/g, "_");
  out += `static const unsigned char ${name}[] = {`;
  const parts = [];
  for (let i = 0; i < data.length; i++) parts.push(data[i]);
  out += parts.join(",");
  out += `};\nstatic const unsigned int ${name}_len = ${data.length};\n`;
}
fs.writeFileSync("C:/proy/zombis/ZamnNative/src/assets_embedded.h", out);
console.log("assets_embedded.h written:", files.length, "assets");
