// Generate sprites.h from sliced blob JSONs + hand-picked frame indices.
const fs = require("fs");
const J = f => JSON.parse(fs.readFileSync(f, "utf8")).blobs;
const zeke = J("zeke_map.json"), julie = J("julie_map.json"), zombie = J("zombie_map.json"),
      vict = J("victims_map.json"), items = J("items_map.json"), door = J("exitdoor_map.json");

const sel = {
  // player walk cycles (right for zeke = mirrored left at runtime).
  // zeke_left blob 49 (f4) faces RIGHT (look-back frame) - excluded; the
  // cycle is stride, contact, stride, contact.
  zeke_down:  [zeke, [14,22,34,22]],
  zeke_left:  [zeke, [16,44,23,44]],
  zeke_up:    [zeke, [24,17,45,17]],
  julie_down: [julie, [0,16,43,68,93]],
  julie_left: [julie, [1,17,44,69,94]],
  julie_up:   [julie, [2,18,45,70,95]],
  julie_right:[julie, [3,19,46,71,96]],
  zom_down:   [zombie, [6,7,8,9]],
  zom_right:  [zombie, [10,11,12,13]],
  zom_up:     [zombie, [14,15,16,17]],
  zom_rise:   [zombie, [19,20,22,24,25]],
  zom_die:    [zombie, [51,52,53]],
  vic_cheer:  [vict, [8,14,18,22]],
  vic_dog:    [vict, [1,2,4,5]],
  vic_soldier:[vict, [30,31,32]],
  vic_kid:    [vict, [55,56,57]],
  vic_tourist:[vict, [28,29]],
  fx_angel:   [vict, [63,64,65]],
  fx_sparkle: [vict, [60,61,62]],
  icon_gun:   [items, [0]],
  icon_medkit:[items, [20]],
  icon_1up:   [items, [25]],
  door_closed:[door, [5]],
  door_open:  [door, [6]],
};

let h = "// generated by gen_header.js - frame rects {x,y,w,h} on source sheets\n";
h += "typedef struct { int x, y, w, h; } Frame;\n\n";
for (const [name, [set, idxs]] of Object.entries(sel)) {
  const fr = idxs.map(i => { const b = set[i]; if (!b) throw new Error(name + " idx " + i); return `{${b.x},${b.y},${b.w},${b.h}}`; });
  h += `static const Frame ${name}[] = { ${fr.join(", ")} };\n`;
  h += `#define ${name}_N ${idxs.length}\n`;
}
fs.writeFileSync("../ZamnNative/src/sprites.h", h);
console.log("sprites.h written:", Object.keys(sel).length, "animation sets");
