// generated by gen_header.js - frame rects {x,y,w,h} on source sheets
typedef struct { int x, y, w, h; } Frame;

static const Frame zeke_down[] = { {86,5,16,36}, {108,4,15,37}, {128,4,16,37}, {108,4,15,37} };
#define zeke_down_N 4
static const Frame zeke_left[] = { {87,44,15,37}, {108,44,13,37}, {127,44,20,37}, {152,44,14,37} };
#define zeke_left_N 4
static const Frame zeke_up[] = { {87,86,16,35}, {108,85,14,36}, {129,86,16,35}, {153,85,14,36} };
#define zeke_up_N 4
static const Frame julie_down[] = { {7,4,20,38}, {9,52,16,38}, {10,102,15,38}, {7,154,16,38}, {7,205,16,38} };
#define julie_down_N 5
static const Frame julie_left[] = { {41,5,18,37}, {40,55,22,36}, {40,103,22,36}, {39,153,20,36}, {39,206,24,35} };
#define julie_left_N 5
static const Frame julie_up[] = { {76,5,20,37}, {76,53,14,37}, {74,101,15,37}, {73,152,14,37}, {74,204,15,37} };
#define julie_up_N 5
static const Frame julie_right[] = { {109,6,18,37}, {105,54,22,36}, {102,103,22,36}, {102,154,20,36}, {96,205,24,35} };
#define julie_right_N 5
static const Frame zom_down[] = { {8,22,27,47}, {41,21,27,48}, {74,21,27,48}, {108,22,27,47} };
#define zom_down_N 4
static const Frame zom_right[] = { {149,23,25,46}, {178,24,29,45}, {212,23,27,46}, {242,24,30,45} };
#define zom_right_N 4
static const Frame zom_up[] = { {286,23,22,46}, {315,23,22,46}, {344,23,22,46}, {375,23,22,46} };
#define zom_up_N 4
static const Frame zom_rise[] = { {11,135,12,6}, {30,128,24,13}, {63,125,32,15}, {148,100,32,41}, {189,94,28,47} };
#define zom_rise_N 5
static const Frame zom_die[] = { {43,154,4,7}, {48,165,34,51}, {61,156,7,5} };
#define zom_die_N 3
static const Frame vic_cheer[] = { {40,109,44,41}, {184,95,44,41}, {280,97,44,41}, {376,103,44,41} };
#define vic_cheer_N 4
static const Frame vic_dog[] = { {4,56,29,27}, {37,54,27,29}, {68,52,28,31}, {100,54,30,29} };
#define vic_dog_N 4
static const Frame vic_soldier[] = { {4,220,32,46}, {40,218,33,48}, {77,218,31,48} };
#define vic_soldier_N 3
static const Frame vic_kid[] = { {37,384,31,29}, {72,379,37,34}, {113,373,46,40} };
#define vic_kid_N 3
static const Frame vic_tourist[] = { {7,167,41,39}, {59,174,41,32} };
#define vic_tourist_N 2
static const Frame fx_angel[] = { {242,430,16,46}, {274,430,22,46}, {312,430,38,46} };
#define fx_angel_N 3
static const Frame fx_sparkle[] = { {101,428,40,45}, {159,439,23,26}, {198,436,28,32} };
#define fx_sparkle_N 3
static const Frame icon_gun[] = { {7,8,16,12} };
#define icon_gun_N 1
static const Frame icon_medkit[] = { {64,89,16,13} };
#define icon_medkit_N 1
static const Frame icon_1up[] = { {36,141,16,16} };
#define icon_1up_N 1
static const Frame door_closed[] = { {178,12,32,48} };
#define door_closed_N 1
static const Frame door_open[] = { {226,12,32,48} };
#define door_open_N 1
